DISTRIBUTION_NAME=ubuntu
DISTRIBUTION_VERSION=22.04
DISTRIBUTION_ARCH=aarch64

HOST_NAME='aio-ceph'
HOST_IP='192.168.5.15'

USER_NAME='ceph'
USER_HOME='/opt/ceph'

LIMA_INSTANCE='aio-ceph'
DATA_DISKS_COUNT='3'
DATA_DISKS_SIZE='100G'

#
# https://docs.ceph.com/en/latest/releases/#active-releases
#
# 02/12/2024
#
CEPH_RELEASE_SQUID='19.2.0'
CEPH_RELEASE_REEF='18.2.4'
CEPH_RELEASE_QUINCY='17.2.8'

CEPH_RELEASE_NAME='squid'
CEPH_RELEASE_VERSION="${CEPH_RELEASE_SQUID}"

CEPH_DASHBOARD_LOGIN=admin
CEPH_DASHBOARD_PASSWORD=admin
